// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1Z9Uf_GX1kM-piOdp4W2gmVMLZHAkdE',
    appId: '1:537552646026:web:e3c31f9125914504a02273',
    messagingSenderId: '537552646026',
    projectId: 'smartsales-bis',
    authDomain: 'smartsales-bis.firebaseapp.com',
    storageBucket: 'smartsales-bis.appspot.com',
    measurementId: 'G-P1VBET7SNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEI1Uq-Rm-TsHj4i8o8Wc_YM0kdeYlrc',
    appId: '1:537552646026:android:d85df56d2cd40f3da02273',
    messagingSenderId: '537552646026',
    projectId: 'smartsales-bis',
    storageBucket: 'smartsales-bis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rPpBMJmUxL0HL7R0qFGSsxIZSFnDq8Y',
    appId: '1:537552646026:ios:0c807583048ead6ea02273',
    messagingSenderId: '537552646026',
    projectId: 'smartsales-bis',
    storageBucket: 'smartsales-bis.appspot.com',
    iosClientId: '537552646026-jtpo255j0oqfisobglh2hs2vjvqe69c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ismartCrm',
  );
}
